# Generated by Django 4.1.7 on 2023-07-07 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_course', models.CharField(max_length=100, unique=True)),
                ('first_course_price', models.IntegerField()),
                ('second_course', models.CharField(max_length=100, unique=True)),
                ('second_course_price', models.IntegerField()),
                ('dessert', models.CharField(max_length=100, unique=True)),
                ('dessert_price', models.IntegerField()),
                ('drink', models.CharField(max_length=100, unique=True)),
                ('drink_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('first_course', models.CharField(blank=True, max_length=30, null=True)),
                ('first_course_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('second_course', models.CharField(blank=True, max_length=30, null=True)),
                ('second_course_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('dessert', models.CharField(blank=True, max_length=30, null=True)),
                ('dessert_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('drink', models.CharField(blank=True, max_length=30, null=True)),
                ('drink_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('first_course', models.CharField(blank=True, max_length=100, null=True)),
                ('first_course_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('second_course', models.CharField(blank=True, max_length=100, null=True)),
                ('second_course_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('dessert', models.CharField(blank=True, max_length=100, null=True)),
                ('dessert_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('drink', models.CharField(blank=True, max_length=100, null=True)),
                ('drink_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
