# Generated by Django 4.1.7 on 2023-05-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_course', models.CharField(max_length=30, unique=True)),
                ('first_course_price', models.IntegerField()),
                ('second_course', models.CharField(max_length=30, unique=True)),
                ('second_course_price', models.IntegerField()),
                ('dessert', models.CharField(max_length=30, unique=True)),
                ('dessert_price', models.IntegerField()),
                ('drink', models.CharField(max_length=30, unique=True)),
                ('drink_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('first_course', models.CharField(max_length=30)),
                ('first_course_quantity', models.IntegerField()),
                ('second_course', models.CharField(max_length=30)),
                ('second_course_quantity', models.IntegerField()),
                ('dessert', models.CharField(max_length=30)),
                ('dessert_quantity', models.IntegerField()),
                ('drink', models.CharField(max_length=30)),
                ('drink_quantity', models.IntegerField()),
            ],
        ),
    ]
