# Generated by Django 4.1.7 on 2023-03-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_user_permissions'),
    ]

    operations = [
    ]
