# Generated by Django 4.1.7 on 2023-03-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20230312_1835'),
    ]

    operations = [
    ]
