# Generated by Django 4.1.7 on 2023-03-13 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20230312_1844'),
        ('myapp', '0005_alter_user_managers'),
    ]

    operations = [
    ]
