# Generated by Django 4.1.7 on 2023-04-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='{{BASE_DIR}}/media/default.png', null=True, upload_to='profile_pics'),
        ),
    ]
