# Generated by Django 4.1.7 on 2023-04-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0010_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='default.png', null=True, upload_to='profile_pics'),
        ),
    ]
