# Generated by Django 4.1.7 on 2023-04-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0011_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_pics'),
        ),
    ]
