# Generated by Django 4.1.7 on 2023-04-21 14:08

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0013_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default=pathlib.PureWindowsPath('C:/default.png'), upload_to='profile_pics'),
        ),
    ]
