# Generated by Django 4.1.7 on 2023-04-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0014_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default="C:\\media'/default.png'", upload_to='profile_pics'),
        ),
    ]
